server:
  port: 8080

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - 'http://localhost:9999'
            allow-credentials: true
            allowed-headers: '*'
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: base-message
            preLogger: true
            postLogger: true
      routes:
        - id: user
          uri: http://localhost:8081/
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<path>.*), /external/user/$\{path} # /user 요청을 /external/user 로 변경
        - id: product
          uri: http://localhost:8082/
          predicates:
            - Path=/product/**
          filters:
            - TokenFilter
            - RewritePath=/product/(?<path>.*), /external/product/$\{path}